1MeV_fullScintList.dat
2p5MeV_fullScintList.dat
AbsorbPosition.C
add_TF1s.C
allPMTpos.dat
Ambe.C
AmbeMPW.C
AmbePartial.C
AnalyBiPo.C
analyBiPo.C
analyCalTimeOfFlight.C
analyClassifier.C
analyMP.C
analyMPearlyHit.C
analyMPmc_rat655new.C
analyMPnew.C
analyMPold.C
analyMPpmts.C
analyMPtRes.C
analyMPW.C
analyMPWnew.C
analyPartialEnergy.C
analyPartialKarin.C
analyPartialKarinMC.C
analyPartialLeon.C
analyPartialMPtRes.C
analyPartialSplitZ.C
analyPartialTres.C
analyPMTs.C
analyRatSNOP.C
analyRatWaterFOM.C
analyScintPMTs.C
AnalysisKarin.C
AnalysisKarinN16.C
AnalysisMCmpw.C
AnalysisN16jeff.C
AnalysisN16mpw.C
AnalysisN16MPWnew.C
AnalysisRatN16.C
analysisRatSimple.C
AnalysisSolar.C
AnalysisSolarJeff1.C
AnalysisSolarMPW.C
AnalysisSolarWater.C
analyTestKarin.C
anim_tResWindow.C
antinuSearch.cc
bellyplate.C
calcuDriveP.py
CalcuN16.C
calcuPhoton.C
CgMinimizer.C
Chi2clean.C
Chi2easyfit.C
Chi2Minimizer.C
compareList.py
compareWf.C
convex.cc
ConvolutionDiscrete.C
ConvolutionHistos.C
ConvolutionHistosNew.C
createN16Macro.py
CutCircle.C
cutLine.C
cut_tail.C
cutTH2F.C
DataAnalysis.C
DataAnalysisN16.C
data_timingFit.C
davidFit.C
deconvolve.py
DerivativeHist.C
docu.C
ellipse.C
example.C
exampleFitChebyshev.C
exampleTKDE.C
extractManip.py
fastInvSquareRoot.C
findBoundary.cc
fitAsymGaus.C
fitBreitWigner.C
fitBreitWignerMore.C
FIT_Ch_Time_all.ratdb
fitDistilledLAB.C
FIT_FITTERAW_cedar.ratdb
FIT_FITTERAW_JP.ratdb
fitMar2020Te.C
FIT_MULTIPATH_partialDev.ratdb
FitterAW.cc
FitterWater.cc
FitterWaterDirection.cc
FitterWaterPosition.cc
FitterWLS_carbonstylie124.cc
FitterWLS.cc
FIT_WLS_Time_all.ratdb
fresnelPlot.C
getMean.C
goProcess.py
highlight.C
histoDerivative.C
IntegralPDF.C
ITR_partial.cc
lightPathCalculator.C
lightPathMC.C
lightPathMCnew.C
lightPathMP.C
linearfit_effectiveVelocity.py
loadMPdb.py
LoopJeff.C
loop_track.C
MergeList.dat
MinimizeDrive4.C
mixedDataSet_tmva.py
ModiMacro.py
ModiSbatch.py
MPdrivePull.C
mpLightPath.C
mpwPDF.C
multiGaus.py
MultiPathAksel.cc
MultiPath_fitSplitZ.cc
MultiPathFitter.cc
multiPathLight.C
MultiPathProcessor.cc
MultiPathProcessor_tResCut.cc
MultiPathScintComplex.cc
MultiPathScintWater_fitSplitZ.cc
MultipleVectors.C
N16SimuList.dat
Nav_Energy.C
Nav_FitOptimize.C
Nav_New1.C
Nav_New.C
NavOpticalTrack.C
NavOpticalTrackNew.C
newLoadData.C
ntuplePartial.C
nucleus.C
NumericalIntegration.C
NumericalMinimization.C
OPTICS_water_bisMSB_all.ratdb
overlayWaveforms.C
PartialFitterMultiPath.cc
PDFMaker_MultiPath.py
PDST_14892_0.ratdb
peaks.C
plot2d.C
plot2d_tool.py
plot3dump.C
plot3scintRegions.C
plotCompare.py
plotCone.C
plotCrates.C
plotDriveCorVsE.C
plotDump.C
PlotHitTimeResiduals.cc
plotNtuple_partialdata.C
plotNtuple_partialMC.C
plotPartialPdf.C
plot_partialResol_oxford.C
plotPDFfitMulti.py
plotScintTiming.py
plotSolar_augToOct2018.C
plotTres.C
plotVgR.C
plotWaveLength.C
printHistBin.C
printSolar.C
printSolarFile.py
processRat.py
processWaveform.C
pyBin.py
pyByte.py
pyJsonLiveTime.py
pyJson.py
pyPlotPartialPDF.py
pyReadByte.py
pyreadcsvNew.py
pyreadcsv.py
pyReadLiveTime.py
quickcheck.C
quickcheck_tRes.C
quickPlotBerkeley.C
ratdb.py
readbinary.C
readcsv.C
readMCA.C
readPMT.C
rebin_range.C
rerange.C
Root_addTF1.C
SaveAngular.C
save.C
scanNtuple.C
scanSolar.C
scanWaterN16.C
scanWaterNtuple.C
SDecompBK.cc
searchSolarJeff1a.C
selectRunGrab.py
shrink_GeoN16SNOMANSourceFactory.cc
smooth.C
SNOP2P2_mc.C
SNOplus_RootPublicationStyle.C
snoPMTpdf.C
solarChPdf.C
solar_fits.C
solarOscillationAnalysis.ipynb
sortFile.py
SourceInfoNov.dat
sph.C
SplitRun.py
sumupWaveforms.C
teLightyield.C
test1.dat
test2.dat
test500ped.dat
test_argument.py
testClear.C
testPartialClassifier.C
testPath.C
thinkbayes.py
timeMatch.C
timeMatchCustom.C
timingFit.C
timingFunc.C
tmvaSolar.py
toyBreitWigner.C
tResPartial.C
trig_time.C
TSLP_14894_0.ratdb
WaterFitterMP.cc
