void loopdir() {
   // example of script to loop on all the objects of a ROOT file directory
   // and print on Postscript all TH1 derived objects
   // This script uses the file generated by tutorial hsimple.C
   //Author: Rene Brun

   TFile *f1 = TFile::Open("My_deap_cal_030681_0000.root");
   TIter next(f1->GetListOfKeys());
   TKey *key;
   // TCanvas c1;
   //c1.Print("hsimple.ps[");
   while ((key = (TKey*)next())) {
      TClass *cl = gROOT->GetClass(key->GetClassName());
      if (!cl->InheritsFrom("TH2")) continue;
      TH2 *h = (TH2*)key->ReadObj();
      TString name = h->GetName();
      // cout<<name<<endl;
      //
      if(name == "EventPos_CosTheta_Phi1")
      {	
        h->Draw("scat=1,same");
	h->SetMarkerStyle(29);
	h->SetMarkerSize(2);
	cout<<name<<endl;
      }	
      // TH1 *h = (TH1*)key->ReadObj();
      // h->Draw();
      // c1.Print("hsimple.ps");
   }
   // c1.Print("hsimple.ps]");
}

